export default [
  { path: '/', redirect: '/welcome' },
  { path: '*', layout: false, component: './404' },
  { path: '/user', layout: false, routes: [{ path: '/user/login', component: './User/Login' }] },
  { path: '/goodsQuote/:sn', layout: false, component: './Quote' },
  { path: '/goodsQuote/:sn/preview', layout: false, component: './Quote' },
  { path: '/goodsQuote/:sn/:version', layout: false, component: './Quote' },
  { path: '/welcome', name: 'welcome', icon: 'smile', component: './Welcome', hideInMenu: true },
  // { icon: 'table', name: '查询表单', path: '/list', component: './TableList' },
  { icon: 'euro', name: '询价单', path: '/inquiries', component: './InquiryList' },
  {
    path: '/inquiries/:name',
    name: '询价单详情',
    hideInMenu: true,
    component: './InquiryList/detail',
  },
  { icon: 'table', name: '商品库', path: '/goods', component: './GoodsList' },
  {
    path: '/goods/:sn',
    name: '商品详情',
    hideInMenu: true,
    component: './GoodsList/detail',
  },
  { icon: 'UnorderedListOutlined', name: '订单', path: '/order', component: './OrderList' },
  { icon: 'AuditOutlined', name: '结算单', path: '/settleOrder', component: './SettleOrderList' },
  {
    path: '/admin',
    icon: 'crown',
    name: '系统管理',
    access: 'canAdmin',
    routes: [
      { path: '/admin', redirect: '/admin/users' },
      { path: '/admin/users', name: '用户管理', component: './Admin' },
      { path: '/admin/shippingConfig', name: '运费配置', component: './ShippingConfig' },
      {
        path: '/admin/shippingConfig/detail/:code',
        hideInMenu: true,
        name: '配置详情',
        component: './ShippingConfig/detail',
      },
      { path: '/admin/paramsConfig', name: '参数配置', component: './ParamsConfig' },
    ],
  },
];
